CREATE DATABASE EMP;
CREATE TABLE EMP_INF(EMP_ID INT NOT NULL, EMP_NAME CHAR(50) NOT NULL,
EMP_SALARY INT NOT NULL ,EMP_DEPARTMENT CHAR(20) ,EMP_DESIGNATION VARCHAR(50) NOT NULL,  );
SELECT * FROM EMP_INF
ALTER TABLE EMP_INF ADD PRIMARY KEY (EMP_ID);
ALTER TABLE EMP_INF ADD CHECK (EMP_AGE>20);
ALTER TABLE EMP_INF ADD CONSTRAINT DF_CITY DEFAULT 'MUMBAI' FOR EMP_CITY;
INSERT INTO EMP_INF VALUES(1, 'RUTVIK', 'PRODUCTION', 'R&D', 50000, 25,'MUMBAI');
INSERT INTO EMP_INF VALUES(2, 'RUTUJA', 'PRODUCTION', 'R&D', 55000, 25,'MUMBAI');
INSERT INTO EMP_INF VALUES(3, 'RUTUPARN', 'TECHNICAL', 'R&D', 60000, 25,'MUMBAI');
INSERT INTO EMP_INF VALUES(4, 'RUPESH', 'TECHNICAL', 'R&D', 19000, 25, 'MUMBAI');
INSERT INTO EMP_INF VALUES(5, 'RUPALI', 'TECHNICAL', 'R&D', 100000, 25, 'MUMBAI');
INSERT INTO EMP_INF VALUES(6, 'REKHA', 'HR', 'ADMIN', 75000, 25, 'MUMBAI');
INSERT INTO EMP_INF VALUES(7, 'RAMESH', 'HR', 'ADMIN', 20000, 25, 'MUMBAI');
INSERT INTO EMP_INF VALUES(8, 'RAVI', 'HR', 'PRODUCTION', 10000, 25, 'MUMBAI');
INSERT INTO EMP_INF VALUES(9, 'RAJENDRA', 'ADMINISTRATION', 'PRODUCTION',15000, 25, 'MUMBAI');
INSERT INTO EMP_INF VALUES(10, 'MOHINI', 'ADMINISTRATION', 'PRODUCTION', 17000,25, 'MUMBAI');
SELECT EMP_ID, EMP_NAME, EMP_DESIGNATION FROM EMP_INFO WHERE EMP_DESIGNATION='MANAGER';
SELECT EMP_ID, EMP_NAME, EMP_SALARY FROM EMP_INFO WHERE EMP_SALARY>10000;